# Generated by Django 4.2.6 on 2023-10-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
